// flow-typed signature: 116103b7ce8edc0660a8c5ae00c8eb62
// flow-typed version: <<STUB>>/dotenv-parse-variables_v^0.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-parse-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-parse-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-parse-variables/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/lib/index' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/test/fixtures/env' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/test/support/index' {
  declare module.exports: any;
}

declare module 'dotenv-parse-variables/test/unit/01-basic.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-parse-variables/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/coverage/lcov-report/block-navigation'>;
}
declare module 'dotenv-parse-variables/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/coverage/lcov-report/prettify'>;
}
declare module 'dotenv-parse-variables/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/coverage/lcov-report/sorter'>;
}
declare module 'dotenv-parse-variables/lib/index.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/lib/index'>;
}
declare module 'dotenv-parse-variables/test/fixtures/env.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/test/fixtures/env'>;
}
declare module 'dotenv-parse-variables/test/support/index.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/test/support/index'>;
}
declare module 'dotenv-parse-variables/test/unit/01-basic.test.js' {
  declare module.exports: $Exports<'dotenv-parse-variables/test/unit/01-basic.test'>;
}
