// flow-typed signature: 09888280197a8c312597cff6dad086c9
// flow-typed version: <<STUB>>/node-hmr_v^1.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-hmr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-hmr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-hmr/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-hmr/index' {
  declare module.exports: $Exports<'node-hmr'>;
}
declare module 'node-hmr/index.js' {
  declare module.exports: $Exports<'node-hmr'>;
}
declare module 'node-hmr/tests/index.test.js' {
  declare module.exports: $Exports<'node-hmr/tests/index.test'>;
}
