// flow-typed signature: 284c047c8c103ccafc7fd47493f9aa83
// flow-typed version: <<STUB>>/override-require_v^1.1.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'override-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'override-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'override-require/declarations/module' {
  declare module.exports: any;
}

declare module 'override-require/dist/overrideRequire' {
  declare module.exports: any;
}

declare module 'override-require/test/overrideRequire' {
  declare module.exports: any;
}

// Filename aliases
declare module 'override-require/declarations/module.js' {
  declare module.exports: $Exports<'override-require/declarations/module'>;
}
declare module 'override-require/dist/overrideRequire.js' {
  declare module.exports: $Exports<'override-require/dist/overrideRequire'>;
}
declare module 'override-require/test/overrideRequire.js' {
  declare module.exports: $Exports<'override-require/test/overrideRequire'>;
}
