// flow-typed signature: f1f1cf0b43855fce47c5fe82a31bcd19
// flow-typed version: <<STUB>>/sails-disk_v^1.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sails-disk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sails-disk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sails-disk/lib/normalize-where' {
  declare module.exports: any;
}

declare module 'sails-disk/test/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sails-disk/index' {
  declare module.exports: $Exports<'sails-disk'>;
}
declare module 'sails-disk/index.js' {
  declare module.exports: $Exports<'sails-disk'>;
}
declare module 'sails-disk/lib/normalize-where.js' {
  declare module.exports: $Exports<'sails-disk/lib/normalize-where'>;
}
declare module 'sails-disk/test/runner.js' {
  declare module.exports: $Exports<'sails-disk/test/runner'>;
}
