// flow-typed signature: 938879ed3ee395f50c9cebe56627df65
// flow-typed version: <<STUB>>/sails-mysql_v^1.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sails-mysql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sails-mysql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sails-mysql/helpers/avg' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/count' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/create-each' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/create' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/define' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/describe' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/destroy' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/drop' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/index' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/join' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/connection/create-manager' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/connection/destroy-manager' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/connection/release-connection' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/connection/spawn-connection' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/connection/spawn-or-lease-connection' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/index' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/compile-statement' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/create-each' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/create' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/destroy' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/initialize-query-cache' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/pre-process-record' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/process-each-record' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/run-native-query' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/run-query' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/query/update' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/schema/build-indexes' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/schema/build-schema' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/private/schema/escape-table-name' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/register-data-store' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/select' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/set-sequence' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/sum' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/teardown' {
  declare module.exports: any;
}

declare module 'sails-mysql/helpers/update' {
  declare module.exports: any;
}

declare module 'sails-mysql/lib/adapter' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/integration/runner' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/create' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/define' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/describe' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/destroy' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/drop' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/find' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/adapter/unit/update' {
  declare module.exports: any;
}

declare module 'sails-mysql/test/support/bootstrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sails-mysql/helpers/avg.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/avg'>;
}
declare module 'sails-mysql/helpers/count.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/count'>;
}
declare module 'sails-mysql/helpers/create-each.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/create-each'>;
}
declare module 'sails-mysql/helpers/create.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/create'>;
}
declare module 'sails-mysql/helpers/define.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/define'>;
}
declare module 'sails-mysql/helpers/describe.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/describe'>;
}
declare module 'sails-mysql/helpers/destroy.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/destroy'>;
}
declare module 'sails-mysql/helpers/drop.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/drop'>;
}
declare module 'sails-mysql/helpers/index.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/index'>;
}
declare module 'sails-mysql/helpers/join.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/join'>;
}
declare module 'sails-mysql/helpers/private/connection/create-manager.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/connection/create-manager'>;
}
declare module 'sails-mysql/helpers/private/connection/destroy-manager.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/connection/destroy-manager'>;
}
declare module 'sails-mysql/helpers/private/connection/release-connection.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/connection/release-connection'>;
}
declare module 'sails-mysql/helpers/private/connection/spawn-connection.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/connection/spawn-connection'>;
}
declare module 'sails-mysql/helpers/private/connection/spawn-or-lease-connection.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/connection/spawn-or-lease-connection'>;
}
declare module 'sails-mysql/helpers/private/index.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/index'>;
}
declare module 'sails-mysql/helpers/private/query/compile-statement.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/compile-statement'>;
}
declare module 'sails-mysql/helpers/private/query/create-each.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/create-each'>;
}
declare module 'sails-mysql/helpers/private/query/create.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/create'>;
}
declare module 'sails-mysql/helpers/private/query/destroy.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/destroy'>;
}
declare module 'sails-mysql/helpers/private/query/initialize-query-cache.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/initialize-query-cache'>;
}
declare module 'sails-mysql/helpers/private/query/pre-process-record.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/pre-process-record'>;
}
declare module 'sails-mysql/helpers/private/query/process-each-record.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/process-each-record'>;
}
declare module 'sails-mysql/helpers/private/query/run-native-query.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/run-native-query'>;
}
declare module 'sails-mysql/helpers/private/query/run-query.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/run-query'>;
}
declare module 'sails-mysql/helpers/private/query/update.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/query/update'>;
}
declare module 'sails-mysql/helpers/private/schema/build-indexes.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/schema/build-indexes'>;
}
declare module 'sails-mysql/helpers/private/schema/build-schema.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/schema/build-schema'>;
}
declare module 'sails-mysql/helpers/private/schema/escape-table-name.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/private/schema/escape-table-name'>;
}
declare module 'sails-mysql/helpers/register-data-store.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/register-data-store'>;
}
declare module 'sails-mysql/helpers/select.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/select'>;
}
declare module 'sails-mysql/helpers/set-sequence.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/set-sequence'>;
}
declare module 'sails-mysql/helpers/sum.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/sum'>;
}
declare module 'sails-mysql/helpers/teardown.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/teardown'>;
}
declare module 'sails-mysql/helpers/update.js' {
  declare module.exports: $Exports<'sails-mysql/helpers/update'>;
}
declare module 'sails-mysql/lib/adapter.js' {
  declare module.exports: $Exports<'sails-mysql/lib/adapter'>;
}
declare module 'sails-mysql/test/adapter/integration/runner.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/integration/runner'>;
}
declare module 'sails-mysql/test/adapter/unit/create.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/create'>;
}
declare module 'sails-mysql/test/adapter/unit/define.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/define'>;
}
declare module 'sails-mysql/test/adapter/unit/describe.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/describe'>;
}
declare module 'sails-mysql/test/adapter/unit/destroy.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/destroy'>;
}
declare module 'sails-mysql/test/adapter/unit/drop.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/drop'>;
}
declare module 'sails-mysql/test/adapter/unit/find.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/find'>;
}
declare module 'sails-mysql/test/adapter/unit/update.js' {
  declare module.exports: $Exports<'sails-mysql/test/adapter/unit/update'>;
}
declare module 'sails-mysql/test/support/bootstrap.js' {
  declare module.exports: $Exports<'sails-mysql/test/support/bootstrap'>;
}
