// flow-typed signature: 07540c6e4abf52cb5f5daff8449f558e
// flow-typed version: <<STUB>>/waterline_v^0.13.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'waterline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'waterline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'waterline/accessible/allowed-validations' {
  declare module.exports: any;
}

declare module 'waterline/accessible/valid-attribute-properties' {
  declare module.exports: any;
}

declare module 'waterline/example/express/express-example' {
  declare module.exports: any;
}

declare module 'waterline/example/raw/raw-example' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/MetaModel' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/add-to-collection' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/archive-one' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/archive' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/avg' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/count' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/create-each' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/create' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/destroy-one' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/destroy' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/find-one' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/find-or-create' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/find' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/remove-from-collection' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/replace-collection' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/stream' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/sum' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/update-one' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/update' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/methods/validate' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/ontology/get-attribute' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/ontology/get-model' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/ontology/is-capable-of-optimized-populate' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/ontology/is-exclusive' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/build-omen' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/forge-adapter-error' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/forge-stage-three-query' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/forge-stage-two-query' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/get-query-modifier-methods' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/help-find' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/build-usage-error' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/expand-where-shorthand' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/GENERIC_HELP_SUFFIX.string' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/is-safe-natural-number' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/is-valid-attribute-name' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-comparison-value' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-constraint' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-criteria' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-new-record' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-pk-value-or-values' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-pk-value' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-sort-clause' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-value-to-set' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/private/normalize-where-clause' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/process-all-records' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/query/verify-model-method-context' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/collection-builder' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/datastore-builder' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/has-schema-check' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/lifecycle-callback-builder' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/reserved-property-names' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/reserved-validation-names' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/transformer-builder' {
  declare module.exports: any;
}

declare module 'waterline/lib/waterline/utils/system/types' {
  declare module.exports: any;
}

declare module 'waterline/test/alter-migrations/strategy.alter.buffers' {
  declare module.exports: any;
}

declare module 'waterline/test/alter-migrations/strategy.alter.schema' {
  declare module.exports: any;
}

declare module 'waterline/test/alter-migrations/strategy.alter.schemaless' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/associations/customer.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/associations/payment.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/cache' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/finalResults' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/joinResults' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/multiple.joins' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/n..1.joins' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/n..m.joins' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/populateResults' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/schema' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/integrator/tables' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/model/context.belongsTo.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/model/context.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/model/context.manyToMany.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/fixtures/model/context.simple.fixture' {
  declare module.exports: any;
}

declare module 'waterline/test/support/migrate.helper' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/afterCreate.create' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/afterCreate.createEach' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/afterCreate.findOrCreate' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/afterDestroy.destroy' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/beforeCreate.create' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/beforeCreate.createEach' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/beforeCreate.findOrCreate' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/callbacks/beforeDestroy.destroy' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/transformations/transformations.initialize' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/transformations/transformations.serialize' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/transformations/transformations.unserialize' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/type-cast/cast.boolean' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/type-cast/cast.json' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/type-cast/cast.number' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/type-cast/cast.ref' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/type-cast/cast.string' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/collection/validations' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/associations/belongsTo' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/associations/hasMany' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/associations/manyToMany' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/associations/populateArray' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/associations/transformedPopulations' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.autocreatedat' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.autoupdatedat' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.avg' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.count' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.count.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.create' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.create.ref' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.create.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.createEach' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.createEach.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.destroy' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.destroy.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.exec' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.find' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.find.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.findOne' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.findOne.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.findOrCreate' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.findOrCreate.transform' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.promises' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.stream' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.sum' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.update' {
  declare module.exports: any;
}

declare module 'waterline/test/unit/query/query.update.transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'waterline/accessible/allowed-validations.js' {
  declare module.exports: $Exports<'waterline/accessible/allowed-validations'>;
}
declare module 'waterline/accessible/valid-attribute-properties.js' {
  declare module.exports: $Exports<'waterline/accessible/valid-attribute-properties'>;
}
declare module 'waterline/example/express/express-example.js' {
  declare module.exports: $Exports<'waterline/example/express/express-example'>;
}
declare module 'waterline/example/raw/raw-example.js' {
  declare module.exports: $Exports<'waterline/example/raw/raw-example'>;
}
declare module 'waterline/lib/waterline.js' {
  declare module.exports: $Exports<'waterline/lib/waterline'>;
}
declare module 'waterline/lib/waterline/MetaModel.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/MetaModel'>;
}
declare module 'waterline/lib/waterline/methods/add-to-collection.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/add-to-collection'>;
}
declare module 'waterline/lib/waterline/methods/archive-one.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/archive-one'>;
}
declare module 'waterline/lib/waterline/methods/archive.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/archive'>;
}
declare module 'waterline/lib/waterline/methods/avg.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/avg'>;
}
declare module 'waterline/lib/waterline/methods/count.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/count'>;
}
declare module 'waterline/lib/waterline/methods/create-each.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/create-each'>;
}
declare module 'waterline/lib/waterline/methods/create.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/create'>;
}
declare module 'waterline/lib/waterline/methods/destroy-one.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/destroy-one'>;
}
declare module 'waterline/lib/waterline/methods/destroy.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/destroy'>;
}
declare module 'waterline/lib/waterline/methods/find-one.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/find-one'>;
}
declare module 'waterline/lib/waterline/methods/find-or-create.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/find-or-create'>;
}
declare module 'waterline/lib/waterline/methods/find.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/find'>;
}
declare module 'waterline/lib/waterline/methods/remove-from-collection.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/remove-from-collection'>;
}
declare module 'waterline/lib/waterline/methods/replace-collection.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/replace-collection'>;
}
declare module 'waterline/lib/waterline/methods/stream.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/stream'>;
}
declare module 'waterline/lib/waterline/methods/sum.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/sum'>;
}
declare module 'waterline/lib/waterline/methods/update-one.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/update-one'>;
}
declare module 'waterline/lib/waterline/methods/update.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/update'>;
}
declare module 'waterline/lib/waterline/methods/validate.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/methods/validate'>;
}
declare module 'waterline/lib/waterline/utils/ontology/get-attribute.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/ontology/get-attribute'>;
}
declare module 'waterline/lib/waterline/utils/ontology/get-model.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/ontology/get-model'>;
}
declare module 'waterline/lib/waterline/utils/ontology/is-capable-of-optimized-populate.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/ontology/is-capable-of-optimized-populate'>;
}
declare module 'waterline/lib/waterline/utils/ontology/is-exclusive.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/ontology/is-exclusive'>;
}
declare module 'waterline/lib/waterline/utils/query/build-omen.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/build-omen'>;
}
declare module 'waterline/lib/waterline/utils/query/forge-adapter-error.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/forge-adapter-error'>;
}
declare module 'waterline/lib/waterline/utils/query/forge-stage-three-query.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/forge-stage-three-query'>;
}
declare module 'waterline/lib/waterline/utils/query/forge-stage-two-query.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/forge-stage-two-query'>;
}
declare module 'waterline/lib/waterline/utils/query/get-query-modifier-methods.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/get-query-modifier-methods'>;
}
declare module 'waterline/lib/waterline/utils/query/help-find.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/help-find'>;
}
declare module 'waterline/lib/waterline/utils/query/private/build-usage-error.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/build-usage-error'>;
}
declare module 'waterline/lib/waterline/utils/query/private/expand-where-shorthand.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/expand-where-shorthand'>;
}
declare module 'waterline/lib/waterline/utils/query/private/GENERIC_HELP_SUFFIX.string.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/GENERIC_HELP_SUFFIX.string'>;
}
declare module 'waterline/lib/waterline/utils/query/private/is-safe-natural-number.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/is-safe-natural-number'>;
}
declare module 'waterline/lib/waterline/utils/query/private/is-valid-attribute-name.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/is-valid-attribute-name'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-comparison-value.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-comparison-value'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-constraint.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-constraint'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-criteria.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-criteria'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-new-record.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-new-record'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-pk-value-or-values.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-pk-value-or-values'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-pk-value.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-pk-value'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-sort-clause.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-sort-clause'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-value-to-set.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-value-to-set'>;
}
declare module 'waterline/lib/waterline/utils/query/private/normalize-where-clause.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/private/normalize-where-clause'>;
}
declare module 'waterline/lib/waterline/utils/query/process-all-records.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/process-all-records'>;
}
declare module 'waterline/lib/waterline/utils/query/verify-model-method-context.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/query/verify-model-method-context'>;
}
declare module 'waterline/lib/waterline/utils/system/collection-builder.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/collection-builder'>;
}
declare module 'waterline/lib/waterline/utils/system/datastore-builder.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/datastore-builder'>;
}
declare module 'waterline/lib/waterline/utils/system/has-schema-check.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/has-schema-check'>;
}
declare module 'waterline/lib/waterline/utils/system/lifecycle-callback-builder.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/lifecycle-callback-builder'>;
}
declare module 'waterline/lib/waterline/utils/system/reserved-property-names.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/reserved-property-names'>;
}
declare module 'waterline/lib/waterline/utils/system/reserved-validation-names.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/reserved-validation-names'>;
}
declare module 'waterline/lib/waterline/utils/system/transformer-builder.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/transformer-builder'>;
}
declare module 'waterline/lib/waterline/utils/system/types.js' {
  declare module.exports: $Exports<'waterline/lib/waterline/utils/system/types'>;
}
declare module 'waterline/test/alter-migrations/strategy.alter.buffers.js' {
  declare module.exports: $Exports<'waterline/test/alter-migrations/strategy.alter.buffers'>;
}
declare module 'waterline/test/alter-migrations/strategy.alter.schema.js' {
  declare module.exports: $Exports<'waterline/test/alter-migrations/strategy.alter.schema'>;
}
declare module 'waterline/test/alter-migrations/strategy.alter.schemaless.js' {
  declare module.exports: $Exports<'waterline/test/alter-migrations/strategy.alter.schemaless'>;
}
declare module 'waterline/test/support/fixtures/associations/customer.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/associations/customer.fixture'>;
}
declare module 'waterline/test/support/fixtures/associations/payment.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/associations/payment.fixture'>;
}
declare module 'waterline/test/support/fixtures/integrator/cache.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/cache'>;
}
declare module 'waterline/test/support/fixtures/integrator/finalResults.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/finalResults'>;
}
declare module 'waterline/test/support/fixtures/integrator/joinResults.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/joinResults'>;
}
declare module 'waterline/test/support/fixtures/integrator/multiple.joins.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/multiple.joins'>;
}
declare module 'waterline/test/support/fixtures/integrator/n..1.joins.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/n..1.joins'>;
}
declare module 'waterline/test/support/fixtures/integrator/n..m.joins.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/n..m.joins'>;
}
declare module 'waterline/test/support/fixtures/integrator/populateResults.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/populateResults'>;
}
declare module 'waterline/test/support/fixtures/integrator/schema.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/schema'>;
}
declare module 'waterline/test/support/fixtures/integrator/tables.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/integrator/tables'>;
}
declare module 'waterline/test/support/fixtures/model/context.belongsTo.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/model/context.belongsTo.fixture'>;
}
declare module 'waterline/test/support/fixtures/model/context.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/model/context.fixture'>;
}
declare module 'waterline/test/support/fixtures/model/context.manyToMany.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/model/context.manyToMany.fixture'>;
}
declare module 'waterline/test/support/fixtures/model/context.simple.fixture.js' {
  declare module.exports: $Exports<'waterline/test/support/fixtures/model/context.simple.fixture'>;
}
declare module 'waterline/test/support/migrate.helper.js' {
  declare module.exports: $Exports<'waterline/test/support/migrate.helper'>;
}
declare module 'waterline/test/unit/callbacks/afterCreate.create.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/afterCreate.create'>;
}
declare module 'waterline/test/unit/callbacks/afterCreate.createEach.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/afterCreate.createEach'>;
}
declare module 'waterline/test/unit/callbacks/afterCreate.findOrCreate.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/afterCreate.findOrCreate'>;
}
declare module 'waterline/test/unit/callbacks/afterDestroy.destroy.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/afterDestroy.destroy'>;
}
declare module 'waterline/test/unit/callbacks/beforeCreate.create.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/beforeCreate.create'>;
}
declare module 'waterline/test/unit/callbacks/beforeCreate.createEach.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/beforeCreate.createEach'>;
}
declare module 'waterline/test/unit/callbacks/beforeCreate.findOrCreate.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/beforeCreate.findOrCreate'>;
}
declare module 'waterline/test/unit/callbacks/beforeDestroy.destroy.js' {
  declare module.exports: $Exports<'waterline/test/unit/callbacks/beforeDestroy.destroy'>;
}
declare module 'waterline/test/unit/collection/transformations/transformations.initialize.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/transformations/transformations.initialize'>;
}
declare module 'waterline/test/unit/collection/transformations/transformations.serialize.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/transformations/transformations.serialize'>;
}
declare module 'waterline/test/unit/collection/transformations/transformations.unserialize.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/transformations/transformations.unserialize'>;
}
declare module 'waterline/test/unit/collection/type-cast/cast.boolean.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/type-cast/cast.boolean'>;
}
declare module 'waterline/test/unit/collection/type-cast/cast.json.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/type-cast/cast.json'>;
}
declare module 'waterline/test/unit/collection/type-cast/cast.number.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/type-cast/cast.number'>;
}
declare module 'waterline/test/unit/collection/type-cast/cast.ref.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/type-cast/cast.ref'>;
}
declare module 'waterline/test/unit/collection/type-cast/cast.string.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/type-cast/cast.string'>;
}
declare module 'waterline/test/unit/collection/validations.js' {
  declare module.exports: $Exports<'waterline/test/unit/collection/validations'>;
}
declare module 'waterline/test/unit/query/associations/belongsTo.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/associations/belongsTo'>;
}
declare module 'waterline/test/unit/query/associations/hasMany.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/associations/hasMany'>;
}
declare module 'waterline/test/unit/query/associations/manyToMany.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/associations/manyToMany'>;
}
declare module 'waterline/test/unit/query/associations/populateArray.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/associations/populateArray'>;
}
declare module 'waterline/test/unit/query/associations/transformedPopulations.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/associations/transformedPopulations'>;
}
declare module 'waterline/test/unit/query/query.autocreatedat.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.autocreatedat'>;
}
declare module 'waterline/test/unit/query/query.autoupdatedat.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.autoupdatedat'>;
}
declare module 'waterline/test/unit/query/query.avg.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.avg'>;
}
declare module 'waterline/test/unit/query/query.count.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.count'>;
}
declare module 'waterline/test/unit/query/query.count.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.count.transform'>;
}
declare module 'waterline/test/unit/query/query.create.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.create'>;
}
declare module 'waterline/test/unit/query/query.create.ref.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.create.ref'>;
}
declare module 'waterline/test/unit/query/query.create.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.create.transform'>;
}
declare module 'waterline/test/unit/query/query.createEach.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.createEach'>;
}
declare module 'waterline/test/unit/query/query.createEach.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.createEach.transform'>;
}
declare module 'waterline/test/unit/query/query.destroy.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.destroy'>;
}
declare module 'waterline/test/unit/query/query.destroy.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.destroy.transform'>;
}
declare module 'waterline/test/unit/query/query.exec.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.exec'>;
}
declare module 'waterline/test/unit/query/query.find.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.find'>;
}
declare module 'waterline/test/unit/query/query.find.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.find.transform'>;
}
declare module 'waterline/test/unit/query/query.findOne.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.findOne'>;
}
declare module 'waterline/test/unit/query/query.findOne.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.findOne.transform'>;
}
declare module 'waterline/test/unit/query/query.findOrCreate.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.findOrCreate'>;
}
declare module 'waterline/test/unit/query/query.findOrCreate.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.findOrCreate.transform'>;
}
declare module 'waterline/test/unit/query/query.promises.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.promises'>;
}
declare module 'waterline/test/unit/query/query.stream.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.stream'>;
}
declare module 'waterline/test/unit/query/query.sum.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.sum'>;
}
declare module 'waterline/test/unit/query/query.update.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.update'>;
}
declare module 'waterline/test/unit/query/query.update.transform.js' {
  declare module.exports: $Exports<'waterline/test/unit/query/query.update.transform'>;
}
